### ISSUE TITLE
Basic help - FatalError Declaration of Asantibanez\LivewireSelect\CarModelSelect::options():

### ISSUE THREAD

**Issue by nathanmay** [asantibanez/livewire-select#25]
Hello!

This component looks like exactly what I need for my project however I am having trouble getting it working so can someone help me on what I am doing wrong?

I have followed the guide in the readme using your example. Trying to create a searchable field however am getting this error:

`Symfony\Component\ErrorHandler\Error\FatalError
Declaration of Asantibanez\LivewireSelect\CarModelSelect::options(): Asantibanez\LivewireSelect\Collection must be compatible with Asantibanez\LivewireSelect\LivewireSelect::options($searchTerm = NULL): Illuminate\Support\Collection`

**Livewire\CarModelSelect.php**
```
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Asantibanez\LivewireSelect\LivewireSelect;

class CarModelSelect extends LivewireSelect
{
      public function options($searchTerm = null) : Collection
      {
        return collect([
            [
                'value' => 'honda',
                'description' => 'Honda',
            ],
            [
                'value' => 'mazda',
                'description' => 'Mazda',
            ],
            [
                'value' => 'tesla',
                'description' => 'Tesla',
            ],
        ]);
      }
}
```
**BladeFile.blade.php**
```
<livewire:car-model-select name="car_model_id" placeholder="Choose a Car Model" :searchable="true" />
```

I even thought maybe I was doing something wrong with the search so tried a basic select:
`  <livewire:car-model-select name="car_brand_id" />`
However I still get the same erorr what am I doing wrong?

I know it will be something silly maybe I just dont understand how this works - Thank you for your help!

**Comment by gbelot2003** [comment]
I have the same problem, is a php issue maybe???

**Comment by niektenhoopen** [comment]
> You just have to import ´use Illuminate\Database\Eloquent\Collection;´

`collect()` does not return an Eloquent Collection but a 'regular' Collection, therefore this should be the solution:
`use Illuminate\Support\Collection;`

I guess this issue can be closed @asantibanez ?
