### ISSUE TITLE
Livewire 2.x

### ISSUE THREAD

**Issue by thomasdominic** [asantibanez/livewire-select#6]
Do you think manage Livewire 2.x with this repo ?

**Comment by muzafarali** [comment]
Hi, it's not working with Livewire 2.x. can you upgrade it..?

**Comment by HavilaQQ** [comment]
https://github.com/asantibanez/livewire-select/pull/5#issuecomment-708153014 should be sometime soon

**Comment by salmanrajz** [comment]
waiting (👍 )

**Comment by Megachill** [comment]
@asantibanez any news on this?
