### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by faxunil** [asantibanez/livewire-select#9]
Hi!
I Started to learn Laravel. ISo maybe the quiestion is strange, but I can't isntall this package.
I'm using Laravel 8.0

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - asantibanez/livewire-select[1.1.0, ..., 1.1.4] require illuminate/support ^6.0|^7.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.13).
    - Root composer.json requires asantibanez/livewire-select ^1.1 -> satisfiable by asantibanez/livewire-select[1.1.0, ..., 1.1.4].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Could you please help?
Thanx
gergely

**Comment by netesy** [comment]
https://github.com/asantibanez/livewire-select/issues/6#issuecomment-714472474 
Its a known issue, the only way you can use it is to downgrade to laravel 7 or wait for the update.
